name: JONGHO LEE
title: AI Product & Research Engineer
description: AI 모델과 업무 시스템 사이를 연결하는 AI Product & Research Engineer
url: https://jongsky.github.io
baseurl: ""
lang: ko
timezone: Asia/Seoul

email: ljhljh0125@gmail.com
github_username: JONGSKY
instagram_username: jongsky_data
linkedin_username: jong-sky

darkmode: false
about_profile_image: ./assets/images/profile_image.jpg

plugins:
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - lib
  - scripts
  - docker-compose.yml
  - README.md
